### ISSUE TITLE
[Service] LND 0.14.2.2

### ISSUE THREAD

**Issue by elvece** [Start9Labs/service-packaging#11]
~~Updated to latest upstream version~~ (moved to https://github.com/Start9Labs/lnd-wrapper/issues/62)
- [x] Converted to use JS procedures
- [x] Neutrino auto switching
- [x] Instructions updated/accurate
- [x] Release notes accurate
- [x] Migration(s) tested, if applicable 
- [x] Merged to master
- [x] Release tag drafted

**Comment by elvece** [comment]
Needs merging for JS procedures: https://github.com/Start9Labs/lnd-wrapper/pull/58

**Comment by Blu-J** [comment]
https://github.com/Start9Labs/lnd-wrapper/pull/65
for the last proxy to undefined
