### ISSUE TITLE
[Service] Thunderhub 0.13.13

### ISSUE THREAD

**Issue by elvece** [Start9Labs/service-packaging#18]
- [x] Updated to latest upstream version
- [x] Converted to use JS procedures
- [x] Instructions updated/accurate
- [x] Release notes accurate
- [x] Migration(s) tested, if applicable 
- [x] Merged to master
- [x] Release tag cut

**Comment by cryptodread** [comment]
does proxy fetch blocks apply to this service? I don't think TH uses proxy.

**Comment by cryptodread** [comment]
updated with health-chk fix and pushed to alpha and beta.
