### ISSUE TITLE
[Service] Bitcoin Core 23.0.0

### ISSUE THREAD

**Issue by elvece** [Start9Labs/service-packaging#8]
- [x] Updated to latest upstream version
- [x] Converted to use JS procedures
- [x] Instructions updated/accurate
- [x] Release notes accurate
- [x] Migration(s) tested
   - [x] downgrade to v22.0.1 from v23 @cryptodread 
   - [x] v21 downgrade and back to v23 @kn0wmad 
- [x] Merged to master
- [x] Release tag drafted

**Comment by Blu-J** [comment]
@dr-bonez Did
- [x] Fix the config

**Comment by kn0wmad** [comment]
v23 -> v21 -> v23 test good (a fix was required)

Updated instructions and release notes
