### ISSUE TITLE
[Service] Proxy 0.3.2.3

### ISSUE THREAD

**Issue by elvece** [Start9Labs/service-packaging#9]
- [x] Updated to latest upstream version (gbci is no longer intercepted in our fork)
- [x] Converted to use JS procedures
- [x] Bug in properties modal - error before first run
- [x] remove fetch blocks
- [x] Instructions updated/accurate
- [x] Release notes accurate
- [x] Migration(s) tested, if applicable 
- [x] Merged to master
- [x] Release tag drafted

**Comment by chrisguida** [comment]
@Blu-J Is the fix for properties pushed up somewhere public?

**Comment by cryptodread** [comment]
@dr-bonez Assigned as Service Owner for Proxy as of {today}

**Comment by elvece** [comment]
@dr-bonez 

- [ ] properties fix
- [ ] tbd config fix
